//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fos.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All monitors.
        /// </summary>
        public static string AllMonitorsMode {
            get {
                return ResourceManager.GetString("AllMonitorsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string ContextExit {
            get {
                return ResourceManager.GetString("ContextExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon iconBlack {
            get {
                object obj = ResourceManager.GetObject("iconBlack", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon iconWhite {
            get {
                object obj = ResourceManager.GetObject("iconWhite", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Internal display.
        /// </summary>
        public static string InternalDisplay {
            get {
                return ResourceManager.GetString("InternalDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove the file and restart fos to fix this..
        /// </summary>
        public static string LoadSettingsErrorDescription {
            get {
                return ResourceManager.GetString("LoadSettingsErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings failed to load from &quot;config.json&quot; file.
        /// </summary>
        public static string LoadSettingsErrorTitle {
            get {
                return ResourceManager.GetString("LoadSettingsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t find supported monitors.
        /// </summary>
        public static string MonitorsNotFound {
            get {
                return ResourceManager.GetString("MonitorsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file may not exist or access to it is denied..
        /// </summary>
        public static string OpenSettingsFileErrorDescription {
            get {
                return ResourceManager.GetString("OpenSettingsFileErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t open settings file.
        /// </summary>
        public static string OpenSettingsFileErrorTitle {
            get {
                return ResourceManager.GetString("OpenSettingsFileErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open settings folder.
        /// </summary>
        public static string OpenSettingsFolder {
            get {
                return ResourceManager.GetString("OpenSettingsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reload list.
        /// </summary>
        public static string ReloadList {
            get {
                return ResourceManager.GetString("ReloadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart.
        /// </summary>
        public static string RestartButton {
            get {
                return ResourceManager.GetString("RestartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string SettingsAbout {
            get {
                return ResourceManager.GetString("SettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changes in new version.
        /// </summary>
        public static string SettingsAboutChanges {
            get {
                return ResourceManager.GetString("SettingsAboutChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check for updates.
        /// </summary>
        public static string SettingsAboutCheckUpdates {
            get {
                return ResourceManager.GetString("SettingsAboutCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error is occured.
        /// </summary>
        public static string SettingsAboutErrorMessage {
            get {
                return ResourceManager.GetString("SettingsAboutErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading update....
        /// </summary>
        public static string SettingsAboutInstalling {
            get {
                return ResourceManager.GetString("SettingsAboutInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Install update.
        /// </summary>
        public static string SettingsAboutInstallUpdate {
            get {
                return ResourceManager.GetString("SettingsAboutInstallUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have latest version of phos.
        /// </summary>
        public static string SettingsAboutNoUpdates {
            get {
                return ResourceManager.GetString("SettingsAboutNoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rate limit exceeded. Please try again later..
        /// </summary>
        public static string SettingsAboutRateLimitError {
            get {
                return ResourceManager.GetString("SettingsAboutRateLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Microsoft Store.
        /// </summary>
        public static string SettingsAboutStoreButton {
            get {
                return ResourceManager.GetString("SettingsAboutStoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can check and install updates from Microsoft Store..
        /// </summary>
        public static string SettingsAboutStoreMessage {
            get {
                return ResourceManager.GetString("SettingsAboutStoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update available.
        /// </summary>
        public static string SettingsAboutUpdateAvailable {
            get {
                return ResourceManager.GetString("SettingsAboutUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version .
        /// </summary>
        public static string SettingsAboutVersion {
            get {
                return ResourceManager.GetString("SettingsAboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Appearance.
        /// </summary>
        public static string SettingsAppearance {
            get {
                return ResourceManager.GetString("SettingsAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string SettingsGeneral {
            get {
                return ResourceManager.GetString("SettingsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatically check for updates.
        /// </summary>
        public static string SettingsGeneralAutoCheck {
            get {
                return ResourceManager.GetString("SettingsGeneralAutoCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Launch at startup.
        /// </summary>
        public static string SettingsGeneralAutoStart {
            get {
                return ResourceManager.GetString("SettingsGeneralAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brightness change latency (ms).
        /// </summary>
        public static string SettingsGeneralBrightnessInterval {
            get {
                return ResourceManager.GetString("SettingsGeneralBrightnessInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brightness change latency in All Monitors mode (ms).
        /// </summary>
        public static string SettingsGeneralBrightnessIntervalAllMonitors {
            get {
                return ResourceManager.GetString("SettingsGeneralBrightnessIntervalAllMonitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brightness change latency when using tray icon (ms).
        /// </summary>
        public static string SettingsGeneralBrightnessIntervalTrayIcon {
            get {
                return ResourceManager.GetString("SettingsGeneralBrightnessIntervalTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string SettingsGeneralLanguage {
            get {
                return ResourceManager.GetString("SettingsGeneralLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System Language.
        /// </summary>
        public static string SettingsGeneralLanguageSystem {
            get {
                return ResourceManager.GetString("SettingsGeneralLanguageSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bottom Center.
        /// </summary>
        public static string SettingsHotkeyBottomCenter {
            get {
                return ResourceManager.GetString("SettingsHotkeyBottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bottom Left.
        /// </summary>
        public static string SettingsHotkeyBottomLeft {
            get {
                return ResourceManager.GetString("SettingsHotkeyBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bottom Right.
        /// </summary>
        public static string SettingsHotkeyBottomRight {
            get {
                return ResourceManager.GetString("SettingsHotkeyBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decrease brightness.
        /// </summary>
        public static string SettingsHotkeyDown {
            get {
                return ResourceManager.GetString("SettingsHotkeyDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hotkey popup location.
        /// </summary>
        public static string SettingsHotkeyLocation {
            get {
                return ResourceManager.GetString("SettingsHotkeyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hotkeys.
        /// </summary>
        public static string SettingsHotkeys {
            get {
                return ResourceManager.GetString("SettingsHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable hotkeys.
        /// </summary>
        public static string SettingsHotkeysEnabled {
            get {
                return ResourceManager.GetString("SettingsHotkeysEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brightness change step.
        /// </summary>
        public static string SettingsHotkeyStep {
            get {
                return ResourceManager.GetString("SettingsHotkeyStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top Center.
        /// </summary>
        public static string SettingsHotkeyTopCenter {
            get {
                return ResourceManager.GetString("SettingsHotkeyTopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top Left.
        /// </summary>
        public static string SettingsHotkeyTopLeft {
            get {
                return ResourceManager.GetString("SettingsHotkeyTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top Right.
        /// </summary>
        public static string SettingsHotkeyTopRight {
            get {
                return ResourceManager.GetString("SettingsHotkeyTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increase brightness.
        /// </summary>
        public static string SettingsHotkeyUp {
            get {
                return ResourceManager.GetString("SettingsHotkeyUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monitors.
        /// </summary>
        public static string SettingsMonitors {
            get {
                return ResourceManager.GetString("SettingsMonitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brightness level limits.
        /// </summary>
        public static string SettingsMonitorsCustomLimits {
            get {
                return ResourceManager.GetString("SettingsMonitorsCustomLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can set brightness level limits to make brightness of different monitors more consistent..
        /// </summary>
        public static string SettingsMonitorsCustomLimitsDescription {
            get {
                return ResourceManager.GetString("SettingsMonitorsCustomLimitsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum.
        /// </summary>
        public static string SettingsMonitorsCustomLimitsMax {
            get {
                return ResourceManager.GetString("SettingsMonitorsCustomLimitsMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum.
        /// </summary>
        public static string SettingsMonitorsCustomLimitsMin {
            get {
                return ResourceManager.GetString("SettingsMonitorsCustomLimitsMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Some settings require a restart to be applied..
        /// </summary>
        public static string SettingsRestartRequired {
            get {
                return ResourceManager.GetString("SettingsRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The settings file contains errors. Restart phos to fix it..
        /// </summary>
        public static string SettingsSchemaErrorDescription {
            get {
                return ResourceManager.GetString("SettingsSchemaErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings schema validation error.
        /// </summary>
        public static string SettingsSchemaErrorTitle {
            get {
                return ResourceManager.GetString("SettingsSchemaErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click the tray icon to open the pop-up..
        /// </summary>
        public static string WelcomeWindowDescription {
            get {
                return ResourceManager.GetString("WelcomeWindowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Got it.
        /// </summary>
        public static string WelcomeWindowOk {
            get {
                return ResourceManager.GetString("WelcomeWindowOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to phos!.
        /// </summary>
        public static string WelcomeWindowTitle {
            get {
                return ResourceManager.GetString("WelcomeWindowTitle", resourceCulture);
            }
        }
    }
}
